import './globals.css'
import { Urbanist } from 'next/font/google'
import Footer from '@/components/footer'
import Navbar from '@/components/navbar'
import ModalProvider from "@/providers/modal-provider";
import ToastProvider from "@/providers/modal-provider"
const font = Urbanist({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        {children}
         <ModalProvider />
         <ToastProvider />
        <Navbar />
        <Footer />
        </body>
    </html>
  )
}
